spring:
  config:
    import: "optional:env[.properties]"
  server:
    port: 8080
  datasource:
    url: jdbc:mysql://${DEFAULT_URL}:3306/${DEFAULT_SCHEMA}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000   # 10초
      validation-timeout: 3000
      maximum-pool-size: 10
  main:
    lazy-initialization: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${DOMAIN_URL}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SOLOJ_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  tourapi:
    key: ${SERVICE_KEY}
    app-name: 혼자옵서예
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      repositories:
        enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.JvmMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.LogbackMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration


jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyForJWTTokenSigningThatIsAtLeast512BitsLongForHS512Algorithm1234567890}
  access-token-expiration: 900 # 15분 (초 단위)
  refresh-token-expiration: 604800 # 7일 (초 단위)

openai:
  model: gpt-4
  secret-key: ${AI_SECRET_KEY}


discord:
  webhooks:
    error: ${DISCORD_WEBHOOK_ERROR:}
    lifecycle: ${DISCORD_WEBHOOK_LIFECYCLE:}

google:
  application:
    credentials: "google-credential.json"


cloud:
  aws:
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}


fcm:
  enabled: ${FCM_ENABLED:true}
  key:
    path: ${FCM_KEY_PATH:firebase/soloj-firbase-key.json}


management:
  metrics:
    enable:
      jvm: true
      system: false   # 시스템 메트릭 꺼짐
      mongo: false    # 몽고 안 씀
      process: false

