spring:
  config:
    import: "optional:env[.properties]"
  server:
    port: 8080
  datasource:
    url: jdbc:mysql://${DEFAULT_URL}:3306/${DEFAULT_SCHEMA}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${DOMAIN_URL}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SOLOJ_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  tourapi:
    key: ${SERVICE_KEY}
    app-name: 혼자옵서예
  data:
    mongodb:
      uri: mongodb://localhost:27017/soloJ
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      database: 0
jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyForJWTTokenSigningThatIsAtLeast512BitsLongForHS512Algorithm1234567890}
  access-token-expiration: 900 # 15분 (초 단위)
  refresh-token-expiration: 604800 # 7일 (초 단위)

openai:
  model: gpt-4
  secret-key: ${AI_SECRET_KEY}


discord:
  webhooks:
    error: ${DISCORD_WEBHOOK_ERROR:}
    lifecycle: ${DISCORD_WEBHOOK_LIFECYCLE:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

